services:
  - type: web
    name: bot-discord
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    runtime: python-3.11
    plan: free
    envVars:
      - key: TOKEN
        sync: false  # Tu ajouteras le TOKEN manuellement dans le dashboard
